language: generic
before_install:
  - DEBIAN_FRONTEND=noninteractive sudo apt-get -y update
  - DEBIAN_FRONTEND=noninteractive sudo apt-get -y install
      build-essential
      git
      shellcheck
script:
  - make lint
  - make && sudo make install && poi --version
