language: generic
before_install:
  - DEBIAN_FRONTEND=noninteractive sudo apt-get -y update
  - DEBIAN_FRONTEND=noninteractive sudo apt-get -y install
      build-essential
      git
      shellcheck
      ruby
  - gem install thor colorize
script:
  - make lint
  - make && make test && sudo make install && poi --version
